// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Analyze(arg1) {
  return window['go']['main']['App']['Analyze'](arg1);
}

export function AnalyzeWith(arg1, arg2) {
  return window['go']['main']['App']['AnalyzeWith'](arg1, arg2);
}

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function BackupDatabase() {
  return window['go']['main']['App']['BackupDatabase']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function DeleteAthlete(arg1) {
  return window['go']['main']['App']['DeleteAthlete'](arg1);
}

export function DeleteTemplate(arg1) {
  return window['go']['main']['App']['DeleteTemplate'](arg1);
}

export function DeleteTest(arg1) {
  return window['go']['main']['App']['DeleteTest'](arg1);
}

export function DownloadAndRunUpdate(arg1) {
  return window['go']['main']['App']['DownloadAndRunUpdate'](arg1);
}

export function ExportCSV(arg1) {
  return window['go']['main']['App']['ExportCSV'](arg1);
}

export function GetAnalysisConfig(arg1) {
  return window['go']['main']['App']['GetAnalysisConfig'](arg1);
}

export function GetAthlete(arg1) {
  return window['go']['main']['App']['GetAthlete'](arg1);
}

export function GetMarkerOptions() {
  return window['go']['main']['App']['GetMarkerOptions']();
}

export function GetProfileOptions(arg1) {
  return window['go']['main']['App']['GetProfileOptions'](arg1);
}

export function GetSteps(arg1) {
  return window['go']['main']['App']['GetSteps'](arg1);
}

export function GetTest(arg1) {
  return window['go']['main']['App']['GetTest'](arg1);
}

export function ImportCSV(arg1, arg2) {
  return window['go']['main']['App']['ImportCSV'](arg1, arg2);
}

export function ListAthletes(arg1) {
  return window['go']['main']['App']['ListAthletes'](arg1);
}

export function ListProfiles(arg1) {
  return window['go']['main']['App']['ListProfiles'](arg1);
}

export function ListTemplates() {
  return window['go']['main']['App']['ListTemplates']();
}

export function ListTests(arg1) {
  return window['go']['main']['App']['ListTests'](arg1);
}

export function OpenReleasePage(arg1) {
  return window['go']['main']['App']['OpenReleasePage'](arg1);
}

export function ParsePaste(arg1) {
  return window['go']['main']['App']['ParsePaste'](arg1);
}

export function RecomputeZones(arg1, arg2, arg3) {
  return window['go']['main']['App']['RecomputeZones'](arg1, arg2, arg3);
}

export function ResetAnalysisConfig(arg1) {
  return window['go']['main']['App']['ResetAnalysisConfig'](arg1);
}

export function RestoreDatabase() {
  return window['go']['main']['App']['RestoreDatabase']();
}

export function SaveAthlete(arg1) {
  return window['go']['main']['App']['SaveAthlete'](arg1);
}

export function SaveSteps(arg1, arg2) {
  return window['go']['main']['App']['SaveSteps'](arg1, arg2);
}

export function SaveTemplate(arg1) {
  return window['go']['main']['App']['SaveTemplate'](arg1);
}

export function SaveTest(arg1) {
  return window['go']['main']['App']['SaveTest'](arg1);
}
